### ISSUE TITLE
Funtionality issues

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/MayDay#122]
Hi Team,
I'd like to note the following issues I faced while testing the application:
1. what is drug search for? I entered "ibuprofen" and got some doctors as a result (which I think is the default results list).
2. advanced search not working. It did not give any results. When I tried again after a while, it was searching for too long.

Also,
I have a couple of questions about the application.
What is User Profile Management for? Is it only limited to login/signup or are you planning to add some more functionalities for the users?

Also, According to my experience, the floating IP addresses provided to the VMs tend to change for some reason. Thus, I'm just curious to know, how are you providing the IP address to each microservice to register itself for the service discovery purpose? Are you hardcoding it in the code or using any dynamic way? 

Thanks,
Shweta

**Comment by KalaRaja** [comment]
@kulsv Advanced search does not work for now, I have mentioned it in the wiki. The 3rd PArty API has some problems with that.

We have dropped the drug search because the drug search 3rd party API is not free anymore. We will remove that option from UI.

The profile management is used only for login and signup.

The floating IP doesn't change, but we haven't hard-coded in the code, it is being picked up by a config file inside UI.

**Comment by kulsv** [comment]
It seems I missed that point in the wiki.

Thanks for clarifying my questions. 

Also, I like the idea of having restricted access to Jenkins for other users. Makes sense. I'd like to implement it for our project too.

Closing this issue.
