### ISSUE TITLE
Peer Review Milestone 2 

### ISSUE THREAD

**Issue by ameyarangal** [airavata-courses/MayDay#124]
Hi Team,

Excellent job with the project implementation and documentation. UI looks good and all the services are running fine. Below are few issues I encountered:

1. Unable to click links about and contact in the navigation bar.

2. Search issue - Search a word and select Drug, it returns doctors in results

3. Cosmetic issue - If the search string is large, the searched feed section doesn’t wrap.

4. Clicking on Sanjeevani, the user is navigated to the login page. I would suggest not to do this.

5. UI - On login the Logged in user name doesn’t show up unless clicking on the avatar. 

6. Purple deploy is being started by red job.

I have few questions mentioned below regarding CI/CD implementation.

Do you have one deploy pipeline that is triggered by each job? If yes, why?
Why is build job and deploy job are different? Any specific reason?

Again excellent job guys.

**Comment by KalaRaja** [comment]
@Ameya05 thanks for valuable feed back.

1. They dont work for now, they are just placeholder.
2. Drug search is being removed from functionality because the 3rd party API is not free anymore.
3. We are working on it.
4. We will remove the click event from that.
5. We will work on it once we reproduce it.
6. whenever a microservice is built, the jenkins deploys entire application to production servers.

build job deploys on dev server, deploy job deploys on production server (used in deploy pipeline).
Unfortunately, because of quota exceeded error, the deploy and build job deploy on dev server for now, we will change this soon.
