### ISSUE TITLE
Peer Review Assignment 1.

### ISSUE THREAD

**Issue by deepakh2810** [airavata-courses/MayDay#50]
Hello Team MayDay,

Things that i noticed after going through the wiki and executing the steps : 

1) All packages that you have installed for python, can be specified in requirements.txt. So in the virtual env, the user could just run a pip install -r requirements.txt and install all the dependencies.
2) The Search functionality does not seem to be working fine. I also observed certain errors in the log of that service.
3) Also, instead of naming the log out button as Sanjeevni, it could have been labelled as Log out. To make the overall user experience better. But the functionality of log out is working perfectly fine.
4) Instead of making the user to checkout to different branches to install every service, you could have delivered a release branch which contained all of your services in a differentiated manner. This is just a suggestion though. Since, both work just fine.
5) In terms of the UI, you could have removed the links, contacts, about which do not have any functionality. Else, the rest of the UI looks good.

I have raised a few issues for the same. Please do review this and get back if i have understood things wrong or if we are not in the same page.

**Comment by KalaRaja** [comment]
@deepakh2810 
Thank for your comments, please find my comments below -
1. will surely do this.
2. can you pull develop-client-rhino and check now
4. we cannot do this because we have Travis CI integrated, I advice you not to do this also, because in future milestone you will have to integrate CI and CD.
5. I thought of doing that, but as professor said, fake it until you make it. :D
