### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/MayDay#94]
Hi Team,

I was reviewing your Assignment 1 release. I had couple of questions
1) I noticed the basic Signup/Sign In has not been implemented. Although Google Oauth is present. Did you guys face any issue while implementing it?
2) I didn't see any DB setup . Arch diag shows a user DB. Again any issues while setting up? 
3) How do I change the location to view Doctors near me. In the console it shows user prompt denied. I don't recollect getting any prompt to select my location. Am I missing something?

Regards,
Raghottam

**Comment by KalaRaja** [comment]
@raghu2094 

1. We had couple of database issues using maven and postgres, see below point.
2. we had implemented DB using postgres, but we were getting permission issues while setting up across different platforms, so we decided to have a distributable database like [H2](http://www.h2database.com/html/main.html). The h2 database is just a jar compared to other bloated databases, it would be easier to deploy across platforms. We decided not to include it for project milestone 1 because it was taking time, so we used files instead of DB. Now, however, we have implemented it and it's ready for milestone 2.
3. The prompt appears top left corner of the browser, most of us just click 'block' and not notice it or it must be some setting of the browser, The system picks up location using browser's navigator geolocator service, We cannot change the location, it takes the current location by default. Can you please try once more in private mode in Firefox or incognito mode in chrome?

**Comment by raghu2094** [comment]
@KalaRaja 
Ok I was able to provide location access in private. For some reason it's taking the current location as  Montgomery County - Coffeyville , KS , US. Is it a known behavior ? 
 I would suggest to keep an option to change location manually if the user forgets to provide access or an option to modify the radius of search for displaying nearby doctors. This can be an enhancement you guys can think about and implement if feasible.

Coming to the feedback. 
It is an interesting project. I was able to run all the microservices without any issue. UI looks good but can be improved. 
Napkin and architecture diagram clearly explains the services of the application. Working of each micro-service and steps for starting the project are well documented.   
It is always a good practice to also document whatever issues/challenges you faced as in your case.  

Overall good job. Hopefully you would have worked on the backlogs from Milestone 1 by now. 
All the best!

**Comment by KalaRaja** [comment]
@raghu2094 

Strange, i will check once, it is showing bloomington to us check the last screenshot in  #49 
I will try the manual location but seems like a long shot to me because google geolocation API is paid and quite expensive.
We will document the issues as well in the wiki, thanks for valuable suggestions.

**Comment by raghu2094** [comment]
Cool.. Look forward to that.
